### ISSUE TITLE
加入插件后build出错

### ISSUE THREAD

**Issue by q759410559** [yccp/cordova-plugin-payments-alipay#1]
BUILD FAILED in 4s
25 actionable tasks: 1 executed, 24 up-to-date
(node:8740) UnhandledPromiseRejectionWarning: Error: cmd: Command failed with exit code 1 Error output:
C:\Users\Administrator\.gradle\caches\transforms-1\files-1.1\support-compat-28.0.0-alpha1.aar\958f18514ef6665a8a428677fe3825c9\res\values\values.xml:20:5-70: AAPT: error: resource android:attr/fontVariationSettings not found.
    
C:\Users\Administrator\.gradle\caches\transforms-1\files-1.1\support-compat-28.0.0-alpha1.aar\958f18514ef6665a8a428677fe3825c9\res\values\values.xml:20:5-70: AAPT: error: resource android:attr/ttcIndex not found.

**Comment by kuyoonjo** [comment]
这个错跟这个插件无关的吧。
